In [1]:
import pandas as pd
import os
import camelot # convert pdf into csv

In [ ]:
# this tell which python version i am using

import sys
print(sys.executable)
print(sys.version)

c:\Users\ASUS\AppData\Local\Programs\Python\Python311\python.exe
3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

In [2]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\asus\appdata\roaming\python\python314\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: C:\Program Files\Python314\python.exe -m pip install --upgrade pip

In [3]:
! pip install camelot-py[cv]

Defaulting to user installation because normal site-packages is not writeable
Collecting camelot-py[cv]
  Using cached camelot_py-1.0.9-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: click>=8.0.1 in c:\users\asus\appdata\roaming\python\python314\site-packages (from camelot-py[cv]) (8.3.1)
Collecting chardet>=5.1.0 (from camelot-py[cv])
  Downloading chardet-7.4.3-cp314-cp314-win_amd64.whl.metadata (9.4 kB)
Requirement already satisfied: numpy>=1.26.1 in c:\users\asus\appdata\roaming\python\python314\site-packages (from camelot-py[cv]) (2.4.3)
Requirement already satisfied: openpyxl>=3.1.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from camelot-py[cv]) (3.1.5)
Collecting pdfminer-six>=20240706 (from camelot-py[cv])
  Using cached pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting pypdf<6.0,>=4.0 (from camelot-py[cv])
  Using cached pypdf-5.9.0-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: pandas>=2.2.2 in c:\users\asus\appdata\roaming\python\python314\site-packages (from camelot-py[cv]) (2.3.3)
Collecting tabulate>=0.9.0 (from camelot-py[cv])
  Downloading tabulate-0.10.0-py3-none-any.whl.metadata (40 kB)
Collecting opencv-python-headless>=4.7.0.68 (from camelot-py[cv])
  Using cached opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting pypdfium2>=4 (from camelot-py[cv])
  Downloading pypdfium2-5.9.0-py3-none-win_amd64.whl.metadata (68 kB)
Requirement already satisfied: pillow>=10.4.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from camelot-py[cv]) (12.1.1)
Requirement already satisfied: colorama in c:\users\asus\appdata\roaming\python\python314\site-packages (from click>=8.0.1->camelot-py[cv]) (0.4.6)
Requirement already satisfied: et-xmlfile in c:\users\asus\appdata\roaming\python\python314\site-packages (from openpyxl>=3.1.0->camelot-py[cv]) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas>=2.2.2->camelot-py[cv]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas>=2.2.2->camelot-py[cv]) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas>=2.2.2->camelot-py[cv]) (2025.3)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pdfminer-six>=20240706->camelot-py[cv]) (3.4.6)
Collecting cryptography>=36.0.0 (from pdfminer-six>=20240706->camelot-py[cv])
  Downloading cryptography-48.0.0-cp311-abi3-win_amd64.whl.metadata (4.3 kB)
Collecting cffi>=2.0.0 (from cryptography>=36.0.0->pdfminer-six>=20240706->camelot-py[cv])
  Downloading cffi-2.0.0-cp314-cp314-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer-six>=20240706->camelot-py[cv])
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.2->camelot-py[cv]) (1.17.0)
Using cached camelot_py-1.0.9-py3-none-any.whl (66 kB)
Using cached pypdf-5.9.0-py3-none-any.whl (313 kB)
Downloading chardet-7.4.3-cp314-cp314-win_amd64.whl (939 kB)
   ---------------------------------------- 0.0/939.6 kB ? eta -:--:--
   ---------------------------------------- 939.6/939.6 kB 8.0 MB/s  0:00:00
Using cached opencv_python_headless-4.13.0.92-cp37-abi3-win_amd64.whl (40.1 MB)
Using cached pdfminer_six-20260107-py3-none-any.whl (6.6 MB)
Downloading cryptography-48.0.0-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------- ----------------------- 1.6/3.8 MB 8.5 MB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 8.5 MB/s  0:00:00
Downloading cffi-2.0.0-cp314-cp314-win_amd64.whl (185 kB)
Downloading pypdfium2-5.9.0-py3-none-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------- ----------------------- 1.6/3.8 MB 7.8 MB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 8.5 MB/s  0:00:00
Downloading tabulate-0.10.0-py3-none-any.whl (39 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: tabulate, pypdfium2, pypdf, pycparser, opencv-python-headless, chardet, cffi, cryptography, pdfminer-six, camelot-py

   ---- -----------------------------------  1/10 [pypdfium2]
   ---- -----------------------------------  1/10 [pypdfium2]
   ---- -----------------------------------  1/10 [pypdfium2]
   ---- -----------------------------------  1/10 [pypdfium2]
   ---- -----------------------------------  1/10 [pypdfium2]
   -------- -------------------------------  2/10 [pypdf]
   -------- -------------------------------  2/10 [pypdf]
   -------- -------------------------------  2/10 [pypdf]
   -------- -------------------------------  2/10 [pypdf]
   -------- -------------------------------  2/10 [pypdf]
   -------- -------------------------------  2/10 [pypdf]
   ------------ ---------------------------  3/10 [pycparser]
   ---------------- -----------------------  4/10 [opencv-python-headless]
   ---------------- -----------------------  4/10 [opencv-python-headless]
   ---------------- -----------------------  4/10 [opencv-python-headless]
   ---------------- -----------------------  4/10 [opencv-python-headless]
   ---------------- -----------------------  4/10 [opencv-python-headless]
   -------------------- -------------------  5/10 [chardet]
   -------------------- -------------------  5/10 [chardet]
   -------------------- -------------------  5/10 [chardet]
   ------------------------ ---------------  6/10 [cffi]
   ------------------------ ---------------  6/10 [cffi]
   ---------------------------- -----------  7/10 [cryptography]
   ---------------------------- -----------  7/10 [cryptography]
   ---------------------------- -----------  7/10 [cryptography]
   ---------------------------- -----------  7/10 [cryptography]
   ---------------------------- -----------  7/10 [cryptography]
   ---------------------------- -----------  7/10 [cryptography]
   ---------------------------- -----------  7/10 [cryptography]
   ---------------------------- -----------  7/10 [cryptography]
   -------------------------------- -------  8/10 [pdfminer-six]
   -------------------------------- -------  8/10 [pdfminer-six]
   -------------------------------- -------  8/10 [pdfminer-six]
   -------------------------------- -------  8/10 [pdfminer-six]
   -------------------------------- -------  8/10 [pdfminer-six]
   ------------------------------------ ---  9/10 [camelot-py]
   ------------------------------------ ---  9/10 [camelot-py]
   ---------------------------------------- 10/10 [camelot-py]

Successfully installed camelot-py-1.0.9 cffi-2.0.0 chardet-7.4.3 cryptography-48.0.0 opencv-python-headless-4.13.0.92 pdfminer-six-20260107 pycparser-3.0 pypdf-5.9.0 pypdfium2-5.9.0 tabulate-0.10.0

WARNING: camelot-py 1.0.9 does not provide the extra 'cv'
  WARNING: The script tabulate.exe is installed in 'C:\Users\ASUS\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pypdfium2.exe is installed in 'C:\Users\ASUS\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script chardetect.exe is installed in 'C:\Users\ASUS\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script camelot.exe is installed in 'C:\Users\ASUS\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: C:\Program Files\Python314\python.exe -m pip install --upgrade pip

In [3]:
import camelot

table = camelot.read_pdf(
    "TGEAPCET_2025_LASTRANKS_FirstPhase.pdf",
    pages="all",
    flavor="lattice"
)
print(table.n)

35

In [4]:
table.export("first.csv",f = "CSV")

In [5]:
print(os.getcwd())

c:\Users\ASUS\OneDrive\Desktop\coding\college recommendation system cutoff bases

In [6]:


all_table = []

for table in table:
    df = table.df
    all_table.append(df)

final_df = pd.concat(all_table, ignore_index=True)

final_df.to_csv("final_first_phase.csv", index=False)

In [8]:
tables_2 = camelot.read_pdf (
    "TGEAPCET_2025_LASTRANKS_SecondPhase.pdf",
    pages = "all",
    flavor="lattice"
)
print (tables_2.n)

34

In [9]:
tables_2.export("second_csv", f = "CSV")

In [10]:
print(os.getcwd())

c:\Users\ASUS\OneDrive\Desktop\coding\college recommendation system cutoff bases

In [11]:
all_table_2 = []
for tables_2 in tables_2:
    df = tables_2.df
    all_table_2.append(df)

final_2_df = pd.concat(all_table_2, ignore_index=True)
final_2_df.to_csv("final_second_phase.csv", index = False)

In [12]:
table_3 = camelot.read_pdf(
    "TGEAPCET_2025_FINALPHASE_LASTRANKS.pdf",
    pages="all",
    flavor="lattice"
)

print(table_3.n)

33

In [13]:
table_3.export("third_csv", f = "CSV")

In [14]:
print(os.getcwd())

c:\Users\ASUS\OneDrive\Desktop\coding\college recommendation system cutoff bases

In [15]:
all_table_3 = []

for table_3 in table_3:
    df = table_3.df
    all_table_3.append(df)

    final_3_df = pd.concat(all_table_3, ignore_index= True)
    final_3_df.to_csv("final_third_phase.csv", index = False)

In [16]:
# UNTIL HERE WE  CONVERT ALL OUR PDF INTO CSV..........

In [2]:
eapcte_df = pd.read_csv("final_third_phase.csv")

In [4]:
eapcte_df.head()

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Inst\n Code,Institute Name,Place,Dist \nCode,Co \nEducation,College \nType,Branch \nCode,Branch Name,OC \nBOYS,OC \nGIRLS,...,SC_I\nGIRLS,SC_II\nBOYS,SC_II\nGIRLS,SC_III\nBOYS,SC_III\nGIRLS,ST \nBOYS,ST \nGIRLS,EWS \nBOYS,EWS \nGIRLS,Affiliated To
1,NaN,AARM AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,HYD,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,38805,38805,...,87026,64346,97072,68760,88071,136225,137171,47591,64129,JNTUH
2,NaN,AARM AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,HYD,COED,PVT,CSM,COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...,23500,23874,...,23874,137635,146095,93866,93866,139967,148259,57355,63565,JNTUH
3,NaN,AARM AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,HYD,COED,PVT,ECE,ELECTRONICS AND COMMUNICATION \nENGINEERING,34682,34682,...,34682,143696,143696,109920,137894,150932,151385,90829,90829,JNTUH
4,NaN,AARM AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,HYD,COED,PVT,EEE,ELECTRICAL AND ELECTRONICS ENGINEERING,97878,97878,...,97878,97878,144789,97878,97878,151513,151513,97878,97878,JNTUH

In [ ]:
# HERE WE START OUR DATA PREPROSSAING/ DATA TRANSFORMATION/ DATA RESHAPING

# DATA RESHAPING MEAN:-- convert raw data into a format that is easier for analysis or ML 

# LOAD CSV
# LOAD CSV
eapcte_df = pd.read_csv("final_third_phase.csv")

# -----------------------------
# SET FIRST ROW AS HEADER
# -----------------------------
eapcte_df.columns = eapcte_df.iloc[0]

# REMOVE FIRST ROW
eapcte_df = eapcte_df[1:].reset_index(drop=True)

# -----------------------------
# CLEAN COLUMN NAMES
# -----------------------------
eapcte_df.columns = (
    eapcte_df.columns
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# -----------------------------
# REMOVE REPEATED HEADER ROWS
# -----------------------------
eapcte_df = eapcte_df[
    ~eapcte_df["Inst Code"]
    .astype(str)
    .str.contains("Inst", case=False, na=False)
]

# -----------------------------
# REMOVE EMPTY ROWS
# -----------------------------
eapcte_df = eapcte_df.dropna(how="all")

# -----------------------------
# RESET INDEX
# -----------------------------
eapcte_df = eapcte_df.reset_index(drop=True)

# -----------------------------
# CHECK CLEANED COLUMNS
# -----------------------------
print(eapcte_df.columns.tolist())

# -----------------------------
# RANK COLUMNS
# -----------------------------
rank_columns = [
    "OC BOYS", "OC GIRLS",

    "BC_A BOYS", "BC_A GIRLS",
    "BC_B BOYS", "BC_B GIRLS",
    "BC_C BOYS", "BC_C GIRLS",
    "BC_D BOYS", "BC_D GIRLS",
    "BC_E BOYS", "BC_E GIRLS",

    "SC_I BOYS", "SC_I GIRLS",
    "SC_II BOYS", "SC_II GIRLS",
    "SC_III BOYS", "SC_III GIRLS",

    "ST BOYS", "ST GIRLS",

    "EWS BOYS", "EWS GIRLS"
]

# -----------------------------
# MELT DATA
# -----------------------------
long_df = eapcte_df.melt(
    id_vars=[
        "Inst Code",
        "Institute Name",
        "Place",
        "Dist Code",
        "Co Education",
        "College Type",
        "Branch Code",
        "Branch Name",
        "Affiliated To"
    ],

    value_vars=rank_columns,

    var_name="Category_Gender",

    value_name="Closing_Rank"
)

# -----------------------------
# SPLIT CATEGORY AND GENDER
# -----------------------------
long_df[["Category", "Gender"]] = (
    long_df["Category_Gender"]
    .str.rsplit(" ", n=1, expand=True)
)

# -----------------------------
# DROP EXTRA COLUMN
# -----------------------------
long_df.drop(columns=["Category_Gender"], inplace=True)

# -----------------------------
# REMOVE NULL VALUES
# -----------------------------
long_df = long_df.dropna(subset=["Closing_Rank"])

# REMOVE EMPTY STRINGS
long_df = long_df[
    long_df["Closing_Rank"]
    .astype(str)
    .str.strip() != ""
]

['Inst Code', 'Institute Name', 'Place', 'Dist Code', 'Co Education', 'College Type', 'Branch Code', 'Branch Name', 'OC BOYS', 'OC GIRLS', 'BC_A BOYS', 'BC_A GIRLS', 'BC_B BOYS', 'BC_B GIRLS', 'BC_C BOYS', 'BC_C GIRLS', 'BC_D BOYS', 'BC_D GIRLS', 'BC_E BOYS', 'BC_E GIRLS', 'SC_I BOYS', 'SC_I GIRLS', 'SC_II BOYS', 'SC_II GIRLS', 'SC_III BOYS', 'SC_III GIRLS', 'ST BOYS', 'ST GIRLS', 'EWS BOYS', 'EWS GIRLS', 'Affiliated To']

In [6]:
long_df.head(1)

,Inst Code,Institute Name,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender
0,NaN,AARM AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,HYD,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,38805,OC,BOYS

In [4]:
# REMOVE COMPLETELY BLANK ROWS
long_df = long_df.dropna(how="all")
# REMOVE EMPTY STRING ROWS
long_df = long_df.replace(r'^\s*$', pd.NA, regex=True)

# REMOVE BLANK ROWS
long_df = long_df.dropna(how="all")

In [5]:
long_df = long_df.reset_index(drop=True)

In [8]:
seat_matrix = pd.read_csv("seat_matrix.csv")

In [9]:
seat_matrix.head()

                                      Institute Name         Branch  Seats
0       AAR Mahaveer Engineering College, Bandlaguda            CSE     47
1       AAR Mahaveer Engineering College, Bandlaguda            ECE     46
2       AAR Mahaveer Engineering College, Bandlaguda            EEE     46
3       AAR Mahaveer Engineering College, Bandlaguda            MEC     46
4  Bhojreddy Engineering College For Women, Saidabad  CSE (AI & ML)     46

In [10]:
new_df = pd.concat([long_df,seat_matrix], axis = 1)

In [30]:
new_df.head(1)

,Inst Code,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender,Seats
0,NaN,BANDLAGUDA,HYD,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,38805,OC,BOYS,47.0

In [12]:
new_df = new_df.drop(["Branch","Institute Name"], axis = 1)

In [13]:
print(seat_matrix.columns.tolist())

['Institute Name', 'Branch', 'Seats']

In [31]:
new_df.head(1)

,Inst Code,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender,Seats
0,NaN,BANDLAGUDA,HYD,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,38805,OC,BOYS,47.0

In [6]:
data_1 = pd.read_csv("final_first_phase.csv")
data_2 = pd.read_csv("final_second_phase.csv")

In [6]:
data_1.head(1)
data_2.head(2)

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,Inst\n Code,Institute Name,Place,Dist \nCode,Co \nEducation,College \nType,Branch \nCode,Branch Name,OC \nBOYS,OC \nGIRLS,...,SC_I\nGIRLS,SC_II\nBOYS,SC_II\nGIRLS,SC_III\nBOYS,SC_III\nGIRLS,ST \nBOYS,ST \nGIRLS,EWS \nBOYS,EWS \nGIRLS,Affiliated To
1,NaN,AARM AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,HYD,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,30248,30248,...,106739,81001,97072,41654,66653,93357,135564,40008,40008,JNTUH

In [7]:
round_1 = long_df.copy()
round_2 = long_df.copy()
round_3 = long_df.copy()

round_1["ROUND"] = 1
round_2["ROUND"] = 2
round_3["ROUND"] = 3

long_df = pd.concat(
    [round_1, round_2, round_3],
    ignore_index=True
)

print(long_df.head())

  Inst Code                         Institute Name       Place Dist Code  \
0       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD
1       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD
2       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD
3       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD
4       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD

  Co Education College Type Branch Code  \
0         COED          PVT         CSE
1         COED          PVT         CSM
2         COED          PVT         ECE
3         COED          PVT         EEE
4         COED          PVT         MEC

                                         Branch Name Affiliated To  \
0                   COMPUTER SCIENCE AND ENGINEERING         JNTUH
1  COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...         JNTUH
2        ELECTRONICS AND COMMUNICATION \nENGINEERING         JNTUH
3             ELECTRICAL AND ELECTRONICS ENGINEERING         JNTUH
4                             MECHANICAL ENGINEERING         JNTUH

  Closing_Rank Category Gender  ROUND
0        38805       OC   BOYS      1
1        23500       OC   BOYS      1
2        34682       OC   BOYS      1
3        97878       OC   BOYS      1
4       102892       OC   BOYS      1

In [12]:
long_df.head(1)

,Inst Code,Institute Name,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender,ROUND
0,NaN,AARM AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,HYD,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,38805,OC,BOYS,1

In [8]:
long_df["year"] = 2025
long_df["Phase"] = "Final"
print(long_df.head())

  Inst Code                         Institute Name       Place Dist Code  \
0       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD
1       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD
2       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD
3       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD
4       NaN  AARM AAR MAHAVEER ENGINEERING COLLEGE  BANDLAGUDA       HYD

  Co Education College Type Branch Code  \
0         COED          PVT         CSE
1         COED          PVT         CSM
2         COED          PVT         ECE
3         COED          PVT         EEE
4         COED          PVT         MEC

                                         Branch Name Affiliated To  \
0                   COMPUTER SCIENCE AND ENGINEERING         JNTUH
1  COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...         JNTUH
2        ELECTRONICS AND COMMUNICATION \nENGINEERING         JNTUH
3             ELECTRICAL AND ELECTRONICS ENGINEERING         JNTUH
4                             MECHANICAL ENGINEERING         JNTUH

  Closing_Rank Category Gender  ROUND  year  Phase
0        38805       OC   BOYS      1  2025  Final
1        23500       OC   BOYS      1  2025  Final
2        34682       OC   BOYS      1  2025  Final
3        97878       OC   BOYS      1  2025  Final
4       102892       OC   BOYS      1  2025  Final

In [9]:
long_df.head(1)

,Inst Code,Institute Name,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender,ROUND,year,Phase
0,NaN,AARM AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,HYD,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,38805,OC,BOYS,1,2025,Final

In [9]:
long_df["Prev_Year_Closing_Rank"] = (
    long_df.groupby(
        [
            "Inst Code",
            "Branch Code",
            "Category",
            "Gender"
        ]
    )["Closing_Rank"]
    .shift(1)
)

In [10]:
long_df["Prev_Year_Closing_Rank"] = (
    long_df.groupby(
        [
            "Inst Code",
            "Branch Code",
            "Category",
            "Gender"
        ]
    )["Prev_Year_Closing_Rank"]
    .transform(lambda x: x.bfill())
)

In [11]:
long_df.tail(100)

,Inst Code,Institute Name,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender,ROUND,year,Phase,Prev_Year_Closing_Rank
59630,VASV,VASAVI COLLEGE OF ENGINEERING,HYDERABAD,HYD,COED,PVT,EEE,ELECTRICAL AND ELECTRONICS ENGINEERING,OU,16617,EWS,GIRLS,3,2025,Final,16617
59631,VASV,VASAVI COLLEGE OF ENGINEERING,HYDERABAD,HYD,COED,PVT,INF,INFORMATION TECHNOLOGY,OU,5602,EWS,GIRLS,3,2025,Final,5602
59632,VASV,VASAVI COLLEGE OF ENGINEERING,HYDERABAD,HYD,COED,PVT,MEC,MECHANICAL ENGINEERING,OU,30349,EWS,GIRLS,3,2025,Final,30349
59633,VBIT,VIGNAN BHARATI INSTITUTE OF \nTECHNOLOGY (AUTO...,GHATKESAR,MDL,COED,PVT,CIV,CIVIL ENGINEERING,JNTUH,108985,EWS,GIRLS,3,2025,Final,108985
59634,VBIT,VIGNAN BHARATI INSTITUTE OF \nTECHNOLOGY (AUTO...,GHATKESAR,MDL,COED,PVT,CSB,COMPUTER SCIENCE AND BUSINESS SYSTEM,JNTUH,36887,EWS,GIRLS,3,2025,Final,36887
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59725,VREC,VIJAYA RURAL ENGINEERING COLLEGE,NIZAMABAD,NZB,COED,PVT,EEE,ELECTRICAL AND ELECTRONICS ENGINEERING,JNTUH,140830,EWS,GIRLS,3,2025,Final,140830
59726,VREC,VIJAYA RURAL ENGINEERING COLLEGE,NIZAMABAD,NZB,COED,PVT,MEC,MECHANICAL ENGINEERING,JNTUH,150154,EWS,GIRLS,3,2025,Final,150154
59727,WITS,WARANGAL INST OF TECHNOLOGY SCIENCE WARANGAL,NaN,HNK,COED,PVT,CIV,CIVIL ENGINEERING,KU,147475,EWS,GIRLS,3,2025,Final,147475
59728,WITS,WARANGAL INST OF TECHNOLOGY SCIENCE WARANGAL,NaN,HNK,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,KU,85259,EWS,GIRLS,3,2025,Final,85259
59729,WITS,WARANGAL INST OF TECHNOLOGY SCIENCE WARANGAL,NaN,HNK,COED,PVT,ECE,ELECTRONICS AND COMMUNICATION \nENGINEERING,KU,90259,EWS,GIRLS,3,2025,Final,90259

In [24]:
long_df.to_csv("update_dataset.csv",index = False)
print("year and phase columns added successfuly!")

year and phase columns added successfuly!

In [12]:
long_df["Closing_Rank"] = (
    long_df["Closing_Rank"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

long_df["Closing_Rank"] = pd.to_numeric(
    long_df["Closing_Rank"],
    errors="coerce"
)

In [13]:
long_df["Prev_Year_Closing_Rank"] = pd.to_numeric(
    long_df["Prev_Year_Closing_Rank"],
    errors="coerce"
)

In [25]:
long_df.head(1)

,Inst Code,Institute Name,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender,ROUND,year,Phase,Prev_Year_Closing_Rank
0,NaN,AARM AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,HYD,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,38805,OC,BOYS,1,2025,Final,NaN

In [23]:
long_df.to_csv("update_dataset.csv",index = False)
print("year and phase columns added successfuly!")

year and phase columns added successfuly!

In [14]:
print(
    long_df[
        long_df["Inst Code"].isna()
    ].head(10)
)

    Inst Code                           Institute Name          Place  \
0         NaN    AARM AAR MAHAVEER ENGINEERING COLLEGE     BANDLAGUDA
1         NaN    AARM AAR MAHAVEER ENGINEERING COLLEGE     BANDLAGUDA
2         NaN    AARM AAR MAHAVEER ENGINEERING COLLEGE     BANDLAGUDA
3         NaN    AARM AAR MAHAVEER ENGINEERING COLLEGE     BANDLAGUDA
4         NaN    AARM AAR MAHAVEER ENGINEERING COLLEGE     BANDLAGUDA
541       NaN  MRCE MALLA REDDY COLLEGE OF ENGINEERING  MYSAMMAGUD\nA
542       NaN  MRCE MALLA REDDY COLLEGE OF ENGINEERING  MYSAMMAGUD\nA
543       NaN  MRCE MALLA REDDY COLLEGE OF ENGINEERING  MYSAMMAGUD\nA
544       NaN  MRCE MALLA REDDY COLLEGE OF ENGINEERING  MYSAMMAGUD\nA
861       NaN    AARM AAR MAHAVEER ENGINEERING COLLEGE     BANDLAGUDA

    Dist Code Co Education College Type Branch Code  \
0         HYD         COED          PVT         CSE
1         HYD         COED          PVT         CSM
2         HYD         COED          PVT         ECE
3         HYD         COED          PVT         EEE
4         HYD         COED          PVT         MEC
541       MDL         COED          PVT         CSD
542       MDL         COED          PVT         CSE
543       MDL         COED          PVT         CSM
544       MDL         COED          PVT         ECE
861       HYD         COED          PVT         CSE

                                           Branch Name Affiliated To  \
0                     COMPUTER SCIENCE AND ENGINEERING         JNTUH
1    COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...         JNTUH
2          ELECTRONICS AND COMMUNICATION \nENGINEERING         JNTUH
3               ELECTRICAL AND ELECTRONICS ENGINEERING         JNTUH
4                               MECHANICAL ENGINEERING         JNTUH
541  COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE)         JNTUH
542                   COMPUTER SCIENCE AND ENGINEERING         JNTUH
543  COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...         JNTUH
544        ELECTRONICS AND COMMUNICATION \nENGINEERING         JNTUH
861                   COMPUTER SCIENCE AND ENGINEERING         JNTUH

     Closing_Rank Category Gender  ROUND  year  Phase  Prev_Year_Closing_Rank
0           38805       OC   BOYS      1  2025  Final                     NaN
1           23500       OC   BOYS      1  2025  Final                     NaN
2           34682       OC   BOYS      1  2025  Final                     NaN
3           97878       OC   BOYS      1  2025  Final                     NaN
4          102892       OC   BOYS      1  2025  Final                     NaN
541         35659       OC   BOYS      1  2025  Final                     NaN
542         23838       OC   BOYS      1  2025  Final                     NaN
543         23837       OC   BOYS      1  2025  Final                     NaN
544         48295       OC   BOYS      1  2025  Final                     NaN
861         38805       OC  GIRLS      1  2025  Final                     NaN

In [15]:
print(
    long_df[
        long_df["Prev_Year_Closing_Rank"].isna()
    ][
        ["Inst Code", "Branch Code"]
    ].head(10)
)

    Inst Code Branch Code
0         NaN         CSE
1         NaN         CSM
2         NaN         ECE
3         NaN         EEE
4         NaN         MEC
324      JBIT         NaN
500      MGIT         NaN
541       NaN         CSD
542       NaN         CSE
543       NaN         CSM

In [16]:
#FIRST

#Do this BEFORE merge:

# REMOVE ROWS WITH MISSING INST CODE
long_df = long_df.dropna(subset=["Inst Code"])

# REMOVE ROWS WITH MISSING BRANCH CODE
long_df = long_df.dropna(subset=["Branch Code"])

# RESET INDEX
long_df = long_df.reset_index(drop=True)

In [17]:
#SECOND

#Some rows have:

#Branch Code = NaN

#like:

#JBIT NaN
#MGIT NaN

#These are also broken extraction rows.

#Remove them:


long_df = long_df[
    long_df["Branch Code"]
    .astype(str)
    .str.strip() != ""
]

In [18]:
#THIRD FIX — Clean ALL important columns

#Before ANY merge:

important_cols = [
    "Inst Code",
    "Branch Code"
]

for col in important_cols:

    long_df[col] = (
        long_df[col]
        .astype(str)
        .str.strip()
        .str.upper()
    )

In [19]:
long_df.head()

,Inst Code,Institute Name,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender,ROUND,year,Phase,Prev_Year_Closing_Rank
0,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CIV,CIVIL ENGINEERING,JNTUH,58226,OC,BOYS,1,2025,Final,58226.0
1,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE),JNTUH,28542,OC,BOYS,1,2025,Final,28542.0
2,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,23801,OC,BOYS,1,2025,Final,23801.0
3,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSM,COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...,JNTUH,22828,OC,BOYS,1,2025,Final,22828.0
4,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSO,COMPUTER SCIENCE AND ENGINEERING (IOT),JNTUH,32808,OC,BOYS,1,2025,Final,32808.0

In [27]:
#   OPENING RANK
# dont use this because here it genrate synthetic data only 
# 
# 
# 


long_df["Opening_Rank"] = (
    long_df["Closing_Rank"] * 0.6
)

In [18]:
long_df.head()

,Inst Code,Institute Name,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender,ROUND,year,Phase,Prev_Year_Closing_Rank,Opening_Rank
0,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CIV,CIVIL ENGINEERING,JNTUH,58226,OC,BOYS,1,2025,Final,58226.0,34935.6
1,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE),JNTUH,28542,OC,BOYS,1,2025,Final,28542.0,17125.2
2,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,23801,OC,BOYS,1,2025,Final,23801.0,14280.6
3,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSM,COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...,JNTUH,22828,OC,BOYS,1,2025,Final,22828.0,13696.8
4,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSO,COMPUTER SCIENCE AND ENGINEERING (IOT),JNTUH,32808,OC,BOYS,1,2025,Final,32808.0,19684.8

In [18]:
long_df.to_csv("EAPCET_dataset.csv",index = False)
print("year and phase columns added successfuly!")

year and phase columns added successfuly!

In [19]:
# make sure numeric
long_df["Closing_Rank"] = pd.to_numeric(long_df["Closing_Rank"], errors="coerce")
long_df["Seats"] = pd.to_numeric(long_df["Seats"], errors="coerce")

# competition ratio
long_df["Competition_Ratio"] = (
    long_df["Closing_Rank"] / long_df["Seats"]
)

KeyError: 'Seats'

In [20]:
#Branch Demand Score

branch_demand = long_df.groupby("Branch Code")["Closing_Rank"].mean()

long_df["Branch_Demand"] = long_df["Branch Code"].map(branch_demand)

In [21]:

#Institute Difficulty Score

inst_difficulty = long_df.groupby("Inst Code")["Closing_Rank"].mean()

long_df["Institute_Difficulty"] = long_df["Inst Code"].map(inst_difficulty)

In [22]:

#Category Competition Pressure

category_pressure = long_df.groupby("Category")["Closing_Rank"].mean()

long_df["Category_Pressure"] = long_df["Category"].map(category_pressure)

In [23]:

#Rank Normalization


from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

long_df["Normalized_Closing_Rank"] = scaler.fit_transform(
    long_df[["Closing_Rank"]]
)

In [24]:
long_df.head()

,Inst Code,Institute Name,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,Category,Gender,ROUND,year,Phase,Prev_Year_Closing_Rank,Branch_Demand,Institute_Difficulty,Category_Pressure,Normalized_Closing_Rank
0,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CIV,CIVIL ENGINEERING,JNTUH,58226,OC,BOYS,1,2025,Final,58226.0,102890.672176,73114.681818,57972.178971,0.378596
1,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE),JNTUH,28542,OC,BOYS,1,2025,Final,28542.0,90618.742158,73114.681818,57972.178971,0.181427
2,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,23801,OC,BOYS,1,2025,Final,23801.0,89064.173844,73114.681818,57972.178971,0.149936
3,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSM,COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...,JNTUH,22828,OC,BOYS,1,2025,Final,22828.0,84415.787071,73114.681818,57972.178971,0.143473
4,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSO,COMPUTER SCIENCE AND ENGINEERING (IOT),JNTUH,32808,OC,BOYS,1,2025,Final,32808.0,81686.204545,73114.681818,57972.178971,0.209763

In [23]:
long_df.to_csv("Updated_EAPCET_dataset.csv",index = False)
print("year and phase columns added successfuly!")

year and phase columns added successfuly!

In [25]:
long_df["No_of_qualifiers"] = 151779

In [26]:

#Create a percentile score showing how competitive a college cutoff rank is relative to all qualified students.

long_df["Competitive_Percentile"] = (
    1- (long_df["Closing_Rank"]/long_df["No_of_qualifiers"])
).clip(lower=0)*100

long_df["Competitive_Percentile"] = long_df["Competitive_Percentile"].round(2)

In [27]:
long_df.head()

,Inst Code,Institute Name,Place,Dist Code,Co Education,College Type,Branch Code,Branch Name,Affiliated To,Closing_Rank,...,ROUND,year,Phase,Prev_Year_Closing_Rank,Branch_Demand,Institute_Difficulty,Category_Pressure,Normalized_Closing_Rank,No_of_qualifiers,Competitive_Percentile
0,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CIV,CIVIL ENGINEERING,JNTUH,58226,...,1,2025,Final,58226.0,102890.672176,73114.681818,57972.178971,0.378596,151779,61.64
1,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE),JNTUH,28542,...,1,2025,Final,28542.0,90618.742158,73114.681818,57972.178971,0.181427,151779,81.20
2,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,JNTUH,23801,...,1,2025,Final,23801.0,89064.173844,73114.681818,57972.178971,0.149936,151779,84.32
3,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSM,COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...,JNTUH,22828,...,1,2025,Final,22828.0,84415.787071,73114.681818,57972.178971,0.143473,151779,84.96
4,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,MDL,COED,PVT,CSO,COMPUTER SCIENCE AND ENGINEERING (IOT),JNTUH,32808,...,1,2025,Final,32808.0,81686.204545,73114.681818,57972.178971,0.209763,151779,78.38

In [28]:
long_df = long_df.drop(
    columns = [
        "Affiliated To",
        "Dist Code"
    ]
)

In [31]:
long_df.head()

,Inst Code,Institute Name,Place,Co Education,College Type,Branch Code,Branch Name,Closing_Rank,Category,Gender,ROUND,year,Phase,Prev_Year_Closing_Rank,Branch_Demand,Institute_Difficulty,Category_Pressure,Normalized_Closing_Rank,No_of_qualifiers,Competitive_Percentile
0,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CIV,CIVIL ENGINEERING,58226,OC,BOYS,1,2025,Final,58226.0,102890.672176,73114.681818,57972.178971,0.378596,151779,61.64
1,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE),28542,OC,BOYS,1,2025,Final,28542.0,90618.742158,73114.681818,57972.178971,0.181427,151779,81.20
2,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,23801,OC,BOYS,1,2025,Final,23801.0,89064.173844,73114.681818,57972.178971,0.149936,151779,84.32
3,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSM,COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...,22828,OC,BOYS,1,2025,Final,22828.0,84415.787071,73114.681818,57972.178971,0.143473,151779,84.96
4,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSO,COMPUTER SCIENCE AND ENGINEERING (IOT),32808,OC,BOYS,1,2025,Final,32808.0,81686.204545,73114.681818,57972.178971,0.209763,151779,78.38

In [32]:
long_df.to_csv("UPDATE_EAPCET_dataset.csv",index = False)
print("year and phase columns added successfuly!")

year and phase columns added successfuly!

In [33]:
#  IMPORT TABLE BY CODE 

# here we get the data from site by code that data is in the html way so

In [ ]:
url = "https://education.sakshi.com/en/eamcet/education-news/telangana-engineering-colleges-list-and-branch-wise-fee-structure-2025-eapcet-counselling-178704"
table = pd.read_html(url)
print(f"Total Table Found: {len(table)}")

long_df = table[0]

long_df.to_csv("TG-EAPCET_fee_structure.csv", index = False)

#The website is blocking pandas with:

#HTTP Error 403: Forbidden 

#This happens because:

#pd.read_html() sends a basic request
#some websites block automated scraping bots

#This is normal.

HTTPError: HTTP Error 403: Forbidden

In [39]:
# TO SOLVE ABOVE PROBLEM WE DO

import requests

url = "https://education.sakshi.com/en/eamcet/education-news/telangana-engineering-colleges-list-and-branch-wise-fee-structure-2025-eapcet-counselling-178704"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers = headers)

table = pd.read_html(response.text)

print(f"Total Table Found: {len(table)}")

df_fee = [0]
print(df_fee.head())

C:\Users\ASUS\AppData\Local\Temp\ipykernel_2476\1800213956.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  table = pd.read_html(response.text)

ValueError: No tables found

In [36]:
! pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\asus\anaconda3\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\asus\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1

In [41]:
! pip install selenium

Collecting selenium
  Downloading selenium-4.44.0-py3-none-any.whl.metadata (7.4 kB)
Collecting certifi>=2026.2.25 (from selenium)
  Downloading certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting typing_extensions<5.0,>=4.15.0 (from selenium)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (24.3.0)
Requirement already satisfied: sortedcontainers in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.7)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\asus\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.17.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\asus\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\asus\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\asus\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.44.0-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.7 MB 2.9 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.7 MB 2.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.7 MB 2.8 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/9.7 MB 2.4 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.7 MB 2.4 MB/s eta 0:00:03
   -------------- ------------------------- 3.4/9.7 MB 2.5 MB/s eta 0:00:03
   --------------- ------------------------ 3.7/9.7 MB 2.3 MB/s eta 0:00:03
   --------------- ------------------------ 3.7/9.7 MB 2.3 MB/s eta 0:00:03
   ----------------- ---------------------- 4.2/9.7 MB 2.0 MB/s eta 0:00:03
   ------------------ --------------------- 4.5/9.7 MB 1.9 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.7 MB 1.9 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.7 MB 1.9 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.7 MB 1.9 MB/s eta 0:00:03
   --------------------- ------------------ 5.2/9.7 MB 1.7 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.7 MB 1.7 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.7 MB 1.7 MB/s eta 0:00:03
   -------------------------- ------------- 6.3/9.7 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 6.8/9.7 MB 1.7 MB/s eta 0:00:02
   ------------------------------ --------- 7.3/9.7 MB 1.7 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.7 MB 1.8 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.7 MB 1.8 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.7 MB 1.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.7 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.7 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.7 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.7 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 1.7 MB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading certifi-2026.5.20-py3-none-any.whl (134 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Installing collected packages: wsproto, urllib3, typing_extensions, outcome, certifi, trio, trio-websocket, selenium

  Attempting uninstall: urllib3

    Found existing installation: urllib3 2.3.0

    Uninstalling urllib3-2.3.0:

      Successfully uninstalled urllib3-2.3.0

   ----- ---------------------------------- 1/8 [urllib3]
   ----- ---------------------------------- 1/8 [urllib3]
  Attempting uninstall: typing_extensions
   ----- ---------------------------------- 1/8 [urllib3]
    Found existing installation: typing_extensions 4.12.2
   ----- ---------------------------------- 1/8 [urllib3]
    Uninstalling typing_extensions-4.12.2:
   ----- ---------------------------------- 1/8 [urllib3]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
      Successfully uninstalled typing_extensions-4.12.2
   ---------- ----------------------------- 2/8 [typing_extensions]
   ---------- ----------------------------- 2/8 [typing_extensions]
  Attempting uninstall: certifi
   ---------- ----------------------------- 2/8 [typing_extensions]
    Found existing installation: certifi 2025.11.12
   ---------- ----------------------------- 2/8 [typing_extensions]
    Uninstalling certifi-2025.11.12:
   ---------- ----------------------------- 2/8 [typing_extensions]
      Successfully uninstalled certifi-2025.11.12
   ---------- ----------------------------- 2/8 [typing_extensions]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------- -------------- 5/8 [trio]
   ------------------------------ --------- 6/8 [trio-websocket]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ----------------------------------- ---- 7/8 [selenium]
   ---------------------------------------- 8/8 [selenium]

Successfully installed certifi-2026.5.20 outcome-1.3.0.post0 selenium-4.44.0 trio-0.33.0 trio-websocket-0.12.2 typing_extensions-4.15.0 urllib3-2.7.0 wsproto-1.3.2

In [37]:

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time

url = "https://engineering.careers360.com/articles/ts-eamcet-fee-structure"

driver = webdriver.Chrome()

driver.get(url)

time.sleep(5)

html = driver.page_source

tables = pd.read_html(html)

print(f"Total tables found: {len(tables)}")

df_fee = tables[0]

print(df_fee.head())

df_fee.to_csv("ts_eamcet_fee_structure.csv", index=False)

driver.quit()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11068\1319879186.py:16: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

Total tables found: 1
                     Institute Name Branch Code   Fees
0  AAR MAHAVEER ENGINEERING COLLEGE         CSE  60000
1  AAR MAHAVEER ENGINEERING COLLEGE         CSM  60000
2  AAR MAHAVEER ENGINEERING COLLEGE         ECE  60000
3  AAR MAHAVEER ENGINEERING COLLEGE         EEE  60000
4  AAR MAHAVEER ENGINEERING COLLEGE         MEC  60000

In [8]:

from selenium import webdriver
import time

url = "https://education.sakshi.com/en/eamcet/education-news/telangana-engineering-colleges-list-and-branch-wise-fee-structure-2025-eapcet-counselling-178704"

driver = webdriver.Chrome()

driver.get(url)

time.sleep(5)

html = driver.page_source

tables = pd.read_html(html)

driver.quit()

# choose correct table number
df = tables[0]

# save directly to csv
df.to_csv("tg_college_fee_data.csv", index=False)

print("CSV saved successfully")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11068\2471119591.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

CSV saved successfully

In [9]:
df.head()

,0,1,2,3,4,5,6,7,8
0,S.No,Institute Code,Institute Name,Place,College,Affil.,Branch,fee,Convener Seats
1,S.No,Institute Code,Institute Name,Place,Type,to,Code,fee,Convener Seats
2,1,AARM,AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,PVT,JNTUH,CSE,60000,42
3,2,AARM,AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,PVT,JNTUH,CSM,60000,42
4,3,AARM,AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,PVT,JNTUH,ECE,60000,42

In [30]:
df =df.reset_index(drop=True)
# REMOVE COMPLETELY BLANK ROWS
df = df.dropna(how="all")
# REMOVE EMPTY STRING ROWS
df = df.replace(r'^\s*$', pd.NA, regex=True)

NameError: name 'df' is not defined

In [11]:
df.head()

,0,1,2,3,4,5,6,7,8
0,S.No,Institute Code,Institute Name,Place,College,Affil.,Branch,fee,Convener Seats
1,S.No,Institute Code,Institute Name,Place,Type,to,Code,fee,Convener Seats
2,1,AARM,AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,PVT,JNTUH,CSE,60000,42
3,2,AARM,AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,PVT,JNTUH,CSM,60000,42
4,3,AARM,AAR MAHAVEER ENGINEERING COLLEGE,BANDLAGUDA,PVT,JNTUH,ECE,60000,42

In [29]:
# remove duplicate header row
df = df[df[0] != "S.No"]

# make first remaining row as column names
df.columns = [
    "S_No",
    "Inst_Code",
    "Institute_Name",
    "Place",
    "College_Type",
    "Affiliated_To",
    "Branch_Code",
    "College_Fee",
    "Convener_Seats"
]

# remove S_No column
df = df.drop(columns=["S_No"])

# keep only required columns
df = df[["College_Fee", "Convener_Seats"]]

# reset index
df = df.reset_index(drop=True)

print(df.head())

NameError: name 'df' is not defined

In [13]:
df.head()

  College_Fee Convener_Seats
0       60000             42
1       60000             42
2       60000             42
3       60000             21
4       60000             21

In [ ]:
# here we merge two data set

long_df = pd.concat([long_df,df], axis = 1)

In [45]:
long_df.head()

,Inst Code,Institute Name,Place,Co Education,College Type,Branch Code,Branch Name,Closing_Rank,Category,Gender,...,year,Phase,Prev_Year_Closing_Rank,Branch_Demand,Institute_Difficulty,Category_Pressure,No_of_qualifiers,Competitive_Percentile,College_Fee,Convener_Seats
0,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CIV,CIVIL ENGINEERING,58226,OC,BOYS,...,2025,Final,58226.0,102890.672176,73114.681818,57972.178971,151779,61.64,60000,42
1,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSD,COMPUTER SCIENCE AND ENGINEERING (DATA \nSCIENCE),28542,OC,BOYS,...,2025,Final,28542.0,90618.742158,73114.681818,57972.178971,151779,81.20,60000,42
2,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSE,COMPUTER SCIENCE AND ENGINEERING,23801,OC,BOYS,...,2025,Final,23801.0,89064.173844,73114.681818,57972.178971,151779,84.32,60000,42
3,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSM,COMPUTER SCIENCE AND ENGINEERING \n(ARTIFICIAL...,22828,OC,BOYS,...,2025,Final,22828.0,84415.787071,73114.681818,57972.178971,151779,84.96,60000,21
4,ACEG,A C E ENGINEERING COLLEGE \n(AUTONOMOUS),GHATKESAR,COED,PVT,CSO,COMPUTER SCIENCE AND ENGINEERING (IOT),32808,OC,BOYS,...,2025,Final,32808.0,81686.204545,73114.681818,57972.178971,151779,78.38,60000,21

In [47]:
long_df.to_csv("UPDATE_EAPCET_dataset.csv",index = False)
print("year and phase columns added successfuly!")

year and phase columns added successfuly!

In [33]:
long_df["Admission_Probability"] = long_df.predict_proba(x)[:,1]

AttributeError: 'DataFrame' object has no attribute 'predict_proba'